### ISSUE TITLE
Crash after re-opening stream

### ISSUE THREAD

**Issue by elecnix** [pleboeuf/ErabliCollecteur#27]
Tue Apr 10 2018 02:22:21 GMT-0400 (EDT) No events received in 660000ms. Re-opening event stream.
    Tue Apr 10 2018 02:22:21 GMT-0400 (EDT) Stream ended! Will re-open.
    /home/nmarchildon/repos/ErabliCollecteur/app.js:160
        db.each(sql, function (err, row) {
           ^

    TypeError: db.each is not a function
        at requestAllDeviceReplay (/home/nmarchildon/repos/ErabliCollecteur/app.js:160:8)
        at Timeout._onTimeout (/home/nmarchildon/repos/ErabliCollecteur/app.js:152:13)
        at ontimeout (timers.js:466:11)
        at tryOnTimeout (timers.js:304:5)
        at Timer.listOnTimeout (timers.js:264:5)

**Comment by pleboeuf** [comment]
Yesterday I had the same problem. Although, this has to be fixed, in production the Collecteur would be restarted automatically since it is run as a service.

**Comment by elecnix** [comment]
I also had it this week.
